baseURL = 'https://blog.asiermarques.com'
languageCode = 'es-ES'
title = 'Asier Marqués'

# Theme configuration
theme = 'serenity-hugo-theme'

[params]
  description = 'Blog personal y reflexiones sobre gestión de ingeniería de software.'
  author = 'Asier Marqués'

  [params.social]
  github = 'https://github.com/asiermarques'
  linkedin = 'https://www.linkedin.com/in/asier/'
  instagram = 'https://www.instagram.com/asiermarques/'
  mail = 'mailto:asiermarques@gmail.com'
  bluesky = 'https://bsky.app/profile/asiermarques.com'
  

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Artículos"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "Sobre mí"
    url = "/info/sobre-mi/"
    weight = 2
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 3

[markup]
  [markup.highlight]
    style = 'monokai'