baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Asier Marqués'

# Theme configuration
theme = 'serenity-hugo-theme'

[params]
  description = 'Blog personal y reflexiones sobre gestión de ingeniería de software.'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Artículos"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "Sobre mí"
    url = "/info/sobre-mi/"
    weight = 2
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 3
